spring:
  application:
    name: url-shortener
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: url-shortener-db

url-shortener:
  expiration-minutes: 1
